commit;

create table stock (
num     NUMBER(5) NOT NULL,
value   NUMBER(5) NOT NULL,
CONSTRAINT stock_pk PRIMARY KEY(num)
);

INSERT INTO STOCK VALUES(1, 390);
INSERT INTO STOCK VALUES(2, 410);
INSERT INTO STOCK VALUES(3, 300);
INSERT INTO STOCK VALUES(4, 260);
INSERT INTO STOCK VALUES(5, 280);
INSERT INTO STOCK VALUES(6, 290);
INSERT INTO STOCK VALUES(7, 310);
INSERT INTO STOCK VALUES(8, 300);
INSERT INTO STOCK VALUES(9, 370);
INSERT INTO STOCK VALUES(10, 110);

SELECT * FROM STOCK;